remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Yilue Qian
logo: assets/figures/bio.jpg
description: qianyilue@outlook.com
theme: jekyll-theme-minimal
head: Yilue Qian
url: ylqian.com